site_name: Sitio web de jguiman958.

nav:
    - Principal: menúprincipal.md
    - Terraform: instalacionterraform.md
    - Prestashop con bitnami: bitnamiprestashop.md
    - Acerca de: about.md
theme: 
    name: material
    logo: assets/logoIAW.jpg
    color: blue grey
    font:
      text: Anta
    features:
     - header.autohide
    features:
     - navigation.footer
